events {}

http {
    server {
        listen 80;

        location /api/auth/ {
            proxy_pass http://auth-service:8080/api/auth/;
        }

        location /api/users/ {
            proxy_pass http://user-service:8080/api/users/;
        }

       location /api/workspaces/ {
           proxy_pass http://workspace-nginx/api/workspaces/;
       }

        location /api/projects/ {
            proxy_pass http://project-service:8080/api/projects/;
        }

        location /api/tasks/ {
            proxy_pass http://task-service:8000/api/tasks/;
        }

        location /api/notifications/ {
            proxy_pass http://notification-service:8080/api/notifications/;
        }
    }
}