import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import ProjectCard from "../components/ProjectCard";
import { getProjects } from "../services/projectApi";
export default function ProjectListPage() {
    const [projects, setProjects] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
    const load = useCallback(async () => { try { setLoading(true); setError(""); setProjects(await getProjects()); } catch (e) { setError(e.response?.data?.message || "Impossible de charger les projets."); } finally { setLoading(false); } }, []);
    useEffect(() => { // eslint-disable-next-line react-hooks/set-state-in-effect
        void load(); }, [load]);
    return <div className="mx-auto max-w-7xl"><header className="mb-8 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-wider text-blue-600">Planification</p><h1 className="mt-1 text-3xl font-bold text-slate-900 sm:text-4xl">Projets</h1><p className="mt-2 text-slate-500">Organisez les projets de vos Workspaces.</p></div><Link to="/projects/create" className="rounded-xl bg-blue-600 px-5 py-3 text-center text-sm font-semibold text-white transition hover:bg-blue-700">+ Créer un projet</Link></header>{loading && <div className="flex min-h-64 items-center justify-center rounded-2xl bg-white text-slate-600"><span className="mr-3 h-5 w-5 animate-spin rounded-full border-2 border-blue-600 border-t-transparent" />Chargement des projets…</div>}{!loading && error && <div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-red-800"><p>{error}</p><button onClick={() => void load()} className="mt-3 rounded-xl border border-red-200 bg-white px-4 py-2 text-sm font-semibold">Réessayer</button></div>}{!loading && !error && projects.length === 0 && <div className="rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><h2 className="text-lg font-semibold">Aucun projet pour le moment</h2><p className="mt-2 text-sm text-slate-500">Créez votre premier projet pour commencer.</p><Link to="/projects/create" className="mt-6 inline-flex rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">Créer un projet</Link></div>}{!loading && !error && projects.length > 0 && <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{projects.map((project) => <ProjectCard key={project.id} project={project} />)}</div>}</div>;
}
